In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree

In [4]:
data=r'C:\Users\HARSHA\Desktop\loan_data_final.csv'
balance_data=pd.read_csv(data,sep=',',header=0)

In [5]:
database_length=len(balance_data)
print(balance_data)

      credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1           all_other    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1           all_other    0.1426       102.92   
5                 1           all_other    0.0788       125.13   
6                 1  debt_consolidation    0.1496       194.02   
7                 1           all_other    0.1114       131.22   
8                 1           all_other    0.1134        87.19   
9                 1  debt_consolidation    0.1221        84.12   
10                1  debt_consolidation    0.1347       360.43   
11                1  debt_consolidation    0.1324       253.58   
12                1  debt_consolidation    0.0859       316.11   
13                1      small_business    0.0714        92.82   
14        

In [6]:
balance_data_shape=balance_data.shape
print(balance_data_shape)

(9578, 14)


In [17]:
#tail() gives the last 4 rows whereas head gives first four rows
print(balance_data.tail())
print(balance_data.head())

      credit.policy             purpose  int.rate  installment  \
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0           all_other    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
9573               2            0        0               1  
9574  

In [7]:
#Separating target variable
X=balance_data.values[:,2:13]
Y=balance_data.values[:,13]
#Split into train and test
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=100)
clf_entropy=DecisionTreeClassifier(criterion='entropy',random_state=100,max_depth=10, min_samples_leaf=5)
#Your y is of type object, so sklearn cannot recognize its type. 
#Add the line y=y.astype('int') right after the line y = train[:, 1].
y_train=y_train.astype(int)
y_test=y_test.astype(int)
clf_entropy.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [8]:
y_predict=clf_entropy.predict(x_test)
y_predict

array([0, 1, 0, ..., 0, 0, 0])

In [48]:
print("Accuracy is ",accuracy_score(y_test,y_predict)*100)

Accuracy is  80.79331941544885


In [9]:
x_test

array([[0.1134, 230.3, 10.59663473, ..., 0, 0, 0],
       [0.1114, 328.04, 10.30895266, ..., 3, 0, 0],
       [0.1379, 306.68, 10.74720759, ..., 0, 0, 0],
       ...,
       [0.1425, 514.49, 10.77895629, ..., 0, 0, 0],
       [0.0894, 476.58, 11.22524339, ..., 2, 0, 0],
       [0.1474, 331.56, 10.91516119, ..., 2, 0, 0]], dtype=object)

In [10]:
x_test[0]

array([0.1134, 230.3, 10.59663473, 9.81, 682, 3030.958333, 6475, 96.6, 0,
       0, 0], dtype=object)